pipeline{
    agent any
    stages{
        stage('Demo Jenkins'){
            steps{
                sh 'echo "Hello from Jenkins Demo"'
            }
        }
        stage('Build and Install'){
            agent{
                docker{
                    image 'node:23-alpine'
                    reuseNode true
                }
            }
            steps{
                sh 'cd jenkins-app/src/'
                sh 'ls -la'
                sh 'npm ci'
                sh 'npm run build'
                sh 'ls'
            }
        }
    }
}