pipeline{
    agent any
    stages{
        stage('Demo Jenkins'){
            steps{
                sh 'echo "Hello from Jenkins Demo"'
            }
        }
        stage('Build and Install'){
            agent{
                docker{
                    image 'node:23-alpine'
                    reuseNode true
                }
            }
            steps{
                dir('jenkins-app/src/'){
                    sh 'npm ci'
                    sh 'npm run build'
                    sh 'ls -la'
                }
            }
        }

        stage('Test'){
            agent{
                docker{
                    image 'node:23-alpine'
                    reuseNode true
                }
            }
            steps{
                dir('jenkins-app/src/'){
                    sh 'npm run test'
                }
            }
        }
    }

    post{
        always{
            junit 'jenkins-app/src/test-results/junit.xml'
        }
    }
}